apiVersion: v1
kind: Secret
metadata:
  name: finalrip-secrets
  namespace: finalrip
  labels:
    app.kubernetes.io/name: finalrip
    app.kubernetes.io/component: config
type: Opaque
data:
  # Base64 encoded values
  mongodb-root-password: MTIzNDU2  # 123456
  redis-password: MTIzNDU2         # 123456
  minio-access-key: aG9tbw==       # homo
  minio-secret-key: aG9tbzExNDUxNA== # homo114514
  server-token: MTE0NTE0           # 114514