version: "2"

linters:
  enable-all: false
  fast: false
  enable:
    - errcheck
    - bodyclose
    - dogsled
    - dupl
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    #    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  disable:
    - unused

formatters:
  enable:
#    - goimports

run:
  timeout: 3m
