version: "3.8"

name: finalrip

networks:
  backend:
    driver: bridge

services:
  mongodb:
    image: mongo:8.0.0-rc13-jammy
    container_name: finalrip-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=finalrip
    volumes:
      - ./allinone/mongodb:/data/db
    networks:
      - backend

  redis:
    image: redis:7.2.5
    container_name: finalrip-redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      --requirepass 123456
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ./allinone/redis:/data
    networks:
      - backend

  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: finalrip-asynqmon
    restart: always
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: 123456
    networks:
      - backend

  oss:
    image: bitnami/minio:2024.7.13
    container_name: finalrip-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: homo
      MINIO_ROOT_PASSWORD: homo114514
      MINIO_DEFAULT_BUCKETS: finalrip:public
    volumes:
      - ./allinone/minio:/bitnami/minio/data
    networks:
      - backend

  consul:
    image: consul:1.15
    container_name: finalrip-consul
    restart: always
    ports:
      - "8500:8500"
    command:
      [
        "consul",
        "agent",
        "-server",
        "-bootstrap",
        "-data-dir",
        "/consul",
        "-ui",
        "-bind",
        "127.0.0.1",
        "-client",
        "0.0.0.0"
      ]
    networks:
      - backend
#  easytier:
#    image: easytier/easytier:latest
#    container_name: easytier
#    restart: always
#    environment:
#      - TZ=Asia/Shanghai
#    privileged: true
#    network_mode: host
#    command: -i 10.126.126.251 --network-name finalrip --network-secret finalrip -e tcp://easytier.public.kkrainbow.top:11010
