version: "3.8"

name: finalrip

networks:
  backend:
    driver: bridge

services:
  worker-encode:
    image: lychee0/finalrip:worker-encode-cuda-dev
    restart: always
    environment:
      #      - FINALRIP_REMOTE_CONFIG_HOST=EASYTIER
      - FINALRIP_REMOTE_CONFIG_HOST=consul:8500
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
              capabilities:
                - gpu
                - utility
                - compute
                - video
    networks:
      - backend
#  easytier:
#    image: easytier/easytier:latest
#    container_name: easytier
#    restart: always
#    environment:
#      - TZ=Asia/Shanghai
#    privileged: true
#    network_mode: host
#    command: -d --network-name finalrip --network-secret finalrip -e tcp://easytier.public.kkrainbow.top:11010

# use script to create network
# export EASYTIER_COMMAND="-d --network-name finalrip --network-secret finalrip -e tcp://easytier.public.kkrainbow.top:11010" && curl -fsSL "https://raw.githubusercontent.com/EutropicAI/FinalRip/main/deploy/easytier/easytier.sh" | bash
