version: "3.8"

name: finalrip

networks:
  backend:
    driver: bridge

#  services:
#  worker-encode:
#    image: lychee0/finalrip-worker-encode:latest
#    container_name: finalrip-worker-encode
#    restart: always
#    environment:
#      - FINALRIP_REMOTE_CONFIG_HOST=EASYTIER
#    networks:
#      - backend

services:
  worker-encode:
    image: lychee0/finalrip-worker-encode-pytorch:dev
    restart: always
    environment:
      #      - FINALRIP_REMOTE_CONFIG_HOST=EASYTIER
      - FINALRIP_REMOTE_CONFIG_HOST=consul:8500
      - FINALRIP_DB_HOST=mongodb
      - FINALRIP_REDIS_HOST=redis
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
              capabilities: [gpu]
    networks:
      - backend
#  easytier:
#    image: easytier/easytier:latest
#    container_name: easytier
#    restart: always
#    environment:
#      - TZ=Asia/Shanghai
#    privileged: true
#    network_mode: host
#    command: -d --network-name finalrip --network-secret finalrip1145141919810 -e tcp://easytier.public.kkrainbow.top:11010

# use script to create network
# export EASYTIER_COMMAND="-d --network-name finalrip --network-secret finalrip1145141919810 -e tcp://easytier.public.kkrainbow.top:11010" && curl -fsSL "https://raw.githubusercontent.com/TensoRaws/FinalRip/main/deploy/easytier/easytier.sh" | bash
