name: Docker Build CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        dockerfile: ["dashboard", "server", "worker-cut", "worker-merge", "worker-encode"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: lychee0
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push for finalrip-worker-encode
        if: matrix.dockerfile == 'worker-encode'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./deploy/${{ matrix.dockerfile }}.dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            lychee0/finalrip-${{ matrix.dockerfile }}:dev
            lychee0/finalrip-${{ matrix.dockerfile }}:cuda-dev
          build-args: |
            BASE_CONTAINER_TAG=cuda-dev
          no-cache: true

      - name: Build and push for other services
        if: matrix.dockerfile != 'worker-encode'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./deploy/${{ matrix.dockerfile }}.dockerfile
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: lychee0/finalrip-${{ matrix.dockerfile }}:dev
          no-cache: true
