name: Docker Build CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        dockerfile: ["server", "worker-cut", "worker-merge"]

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/${{ matrix.dockerfile }}.dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: lychee0/finalrip-${{ matrix.dockerfile }}:dev
