name: CI-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - LICENSE
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
  workflow_dispatch:

jobs:
  unit-test:
    strategy:
      matrix:
        os-version: ["ubuntu-latest"]

    runs-on: ${{ matrix.os-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Test
        run: |
          make test
