name: CI-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - LICENSE
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
  workflow_dispatch:

jobs:
  backend:
    strategy:
      matrix:
        os-version: ["ubuntu-latest"]

    runs-on: ${{ matrix.os-version }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Test
        run: |
          make test

  frontend:
    strategy:
      matrix:
        os-version: ["ubuntu-latest"]

    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Test
        run: |
          cd dashboard
          pnpm install
          pnpm run lint
          pnpm run typecheck
