name: docker build CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        dockerfile: ["server", "worker-cut", "worker-encode", "worker-merge"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push - Encode
        if: matrix.dockerfile == 'worker-encode'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/${{ matrix.dockerfile }}.dockerfile
          platforms: linux/amd64
          push: true
          tags: lychee0/finalrip-${{ matrix.dockerfile }}:dev

      - name: Build and push
        if: matrix.dockerfile != 'worker-encode'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/${{ matrix.dockerfile }}.dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: lychee0/finalrip-${{ matrix.dockerfile }}:dev
