name: Release

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

jobs:
  docker:
    strategy:
      matrix:
        dockerfile: ["server", "worker-cut", "worker-merge"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            lychee0/finalrip-${{ matrix.dockerfile }}
          tags: |
            latest
            ${{ github.ref_name }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./deploy/${{ matrix.dockerfile }}.dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          no-cache: true

  github:
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Release
        uses: softprops/action-gh-release@v2
