name: Release

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

jobs:
  docker:
    strategy:
      matrix:
        dockerfile: ["dashboard", "server", "worker-cut", "worker-merge", "worker-encode"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker # use local image for chain builds

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lychee0
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push for finalrip-worker-encode
        if: matrix.dockerfile == 'worker-encode'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./deploy/${{ matrix.dockerfile }}.dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            lychee0/finalrip-${{ matrix.dockerfile }}:latest
            lychee0/finalrip-${{ matrix.dockerfile }}:cuda
            lychee0/finalrip-${{ matrix.dockerfile }}:cuda-${{ github.ref_name }}
          no-cache: true

      - name: Build and push for other services
        if: matrix.dockerfile != 'worker-encode'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./deploy/${{ matrix.dockerfile }}.dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            lychee0/finalrip-${{ matrix.dockerfile }}:latest
            lychee0/finalrip-${{ matrix.dockerfile }}:${{ github.ref_name }}
          no-cache: true

  github:
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Release
        uses: softprops/action-gh-release@v2
